#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $DIR/config.ini


hour=$(( $((10#$(date +'%H')))*1 ))
minute=$(( $((10#$(date +'%M')))*1 ))
lastminute=$(( minute-1 ))

while true ; do


	if [ $((minute)) -gt $((lastminute)) ]; then
	
		/usr/bin/php $DIR/heating/heating.php

		case 0 in

		# svaki sat
		$(( minute )))
		;;

		# svakih 5 minuta
		$(( minute%5 )))
			# /usr/bin/php $DIR/lan/lan.php
			$DIR/homebrain hbrain wakecheck
		;;

		# svaki put
		*)
		;;

		esac
		
		# svako jutro u 4:15
		if [ $((hour)) -eq 4 -a $((minute)) -eq 15 ]; then
		
			/srv/HomeBrain/dbbackup.php
			# /srv/HomeBrain/lan/dbbackup.php
			/srv/HomeBrain/heating/getTempSet.php
			/srv/HomeBrain/heating/dbbackup.php

			sudo /sbin/shutdown -r now	
		fi
	fi

	lastminute=$(( minute ))
	sleep 45s

	hour=$(( $((10#$(date +'%H')))*1 ))
	minute=$(( $((10#$(date +'%M')))*1 ))

done
