#!/bin/bash

apiurl='http://10.10.10.10/'
word=HomeBrain
wlen=${#word}
rnd=$((RANDOM % wlen))
timestamp=$(date +%s)
secToken=$(echo -n ${word:rnd:1}$((timestamp / 20)) | md5sum | cut -d" " -f1)


if [ "$1" == "th" ]; then
        shift
        curl --data 'secToken='$secToken'&param1='"$3"'&param2='"$4" $apiurl"$1"'/'"$2" & 2> /dev/null;
else
        curl --data 'secToken='$secToken'&param1='"$3"'&param2='"$4" $apiurl"$1"'/'"$2" 2> /dev/null;
fi
