#!/bin/bash

/srv/HomeBrain/lan/kodiWake.sh

# sck1 on
#/srv/HomeBrain/IR/kmap_433 sock1_on

irsend SEND_START SonyTV POWER
sleep 1
irsend SEND_STOP SonyTV POWER

irsend SEND_ONCE Yamaha SYSTEM_POWER
sleep 1;
irsend SEND_ONCE Yamaha D-TV_CBL_INPUT
